import Head from 'next/head'
import { Provider } from 'react-redux'
import Header from '../src/components/Header/Header'
import '../styles/globals.css'
import '../styles/reset.css'
import '../styles/MarkDownEditor.css';
import '../styles/library.scss';
import '../styles/animations.scss';
import store from '../src/store/index';

function MyApp({ Component, pageProps }) {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <Provider store={store}>

      <Header />

      <Component {...pageProps} />
        
      <footer>
          
      </footer>
      
    </Provider>
    
  </>
}

export default MyApp
